### ISSUE TITLE
Failure creating dynamic model definition. #<ActiveRecord::StatementInvalid: PG::UndefinedTable: ERROR:  relation "test_rc80456479990449_recs" does not exist

### ISSUE THREAD

**Issue by melonistic** [melonistic/restructure#11]
2023-03-07 09:31:41 -0500 setup_test_app
Failure creating dynamic model definition. #<ActiveRecord::StatementInvalid: PG::UndefinedTable: ERROR:  relation "test_rc80456479990449_recs" does not exist
LINE 8:                WHERE a.attrelid = '"test_rc80456479990449_re...
                                          ^
:               SELECT a.attname, format_type(a.atttypid, a.atttypmod),
                     pg_get_expr(d.adbin, d.adrelid), a.attnotnull, a.atttypid, a.atttypmod,
                     c.collname, col_description(a.attrelid, a.attnum) AS comment
                FROM pg_attribute a
                LEFT JOIN pg_attrdef d ON a.attrelid = d.adrelid AND a.attnum = d.adnum
                LEFT JOIN pg_type t ON a.atttypid = t.oid
                LEFT JOIN pg_collation c ON a.attcollation = c.oid AND a.attcollation <> t.typcollation
               WHERE a.attrelid = '"test_rc80456479990449_recs"'::regclass
                 AND a.attnum > 0 AND NOT a.attisdropped
               ORDER BY a.attnum
>
/root/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/activerecord-5.2.8.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:63:in `exec'
/root/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/activerecord-5.2.8.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:63:in `block (2 levels) in query'
/root/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/activesupport-5.2.8.1/lib/active_support/dependencies/interlock.rb:48:in `block in permit_concurrent_loads'
/root/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/activesupport-5.2.8.1/lib/active_support/concurrency/share_lock.rb:187:in `yield_shares'
/root/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/activesupport-5.2.8.1/lib/active_support/dependencies/interlock.rb:47:in `permit_concurrent_loads'
/root/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/activerecord-5.2.8.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:62:in `block in query'
/root/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/activerecord-5.2.8.1/lib/active_record/connection_adapters/abstract_adapter.rb:581:in `block (2 levels) in log'
/root/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/activesupport-5.2.8.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:26:in `block (2 levels) in synchronize'
/root/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/activesupport-5.2.8.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
/root/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/activesupport-5.2.8.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
/root/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/activesupport-5.2.8.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
/root/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/activesupport-5.2.8.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
/root/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/activerecord-5.2.8.1/lib/active_record/connection_adapters/abstract_adapter.rb:580:in `block in log'
/root/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/activesupport-5.2.8.1/lib/active_support/notifications/instrumenter.rb:23:in `instrument'
/root/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/activerecord-5.2.8.1/lib/active_record/connection_adapters/abstract_adapter.rb:571:in `log'
/root/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/activerecord-5.2.8.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:61:in `query'
/root/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/activerecord-5.2.8.1/lib/active_record/connection_adapters/postgresql_adapter.rb:757:in `column_definitions'
/root/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/activerecord-5.2.8.1/lib/active_record/connection_adapters/abstract/schema_statements.rb:113:in `columns'
/root/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/activerecord-5.2.8.1/lib/active_record/connection_adapters/schema_cache.rb:69:in `columns'
/root/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/activerecord-5.2.8.1/lib/active_record/connection_adapters/schema_cache.rb:75:in `columns_hash'
/root/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/activerecord-5.2.8.1/lib/active_record/model_schema.rb:466:in `load_schema!'
/root/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/activerecord-5.2.8.1/lib/active_record/attributes.rb:234:in `load_schema!'
/root/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/activerecord-5.2.8.1/lib/active_record/attribute_decorators.rb:51:in `load_schema!'
/root/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/activerecord-5.2.8.1/lib/active_record/model_schema.rb:459:in `block in load_schema'
/root/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/activerecord-5.2.8.1/lib/active_record/model_schema.rb:456:in `synchronize'
/root/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/activerecord-5.2.8.1/lib/active_record/model_schema.rb:456:in `load_schema'
/root/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/activerecord-5.2.8.1/lib/active_record/model_schema.rb:346:in `attribute_types'
/root/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/activerecord-5.2.8.1/lib/active_record/attribute_methods.rb:164:in `attribute_names'
/output/restructure/app/models/concerns/user_handler.rb:35:in `block in <module:UserHandler>'
/root/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/activesupport-5.2.8.1/lib/active_support/concern.rb:122:in `class_eval'
/root/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/activesupport-5.2.8.1/lib/active_support/concern.rb:122:in `append_features'
/output/restructure/app/models/dynamic_model.rb:201:in `include'
/output/restructure/app/models/dynamic_model.rb:201:in `generate_model'
/output/restructure/app/models/dynamic/def_generator.rb:37:in `block in define_models'
/root/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/activerecord-5.2.8.1/lib/active_record/relation/delegation.rb:71:in `each'
/root/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/activerecord-5.2.8.1/lib/active_record/relation/delegation.rb:71:in `each'
/output/restructure/app/models/dynamic/def_generator.rb:36:in `define_models'
/output/restructure/app/models/activity_log.rb:526:in `preload'
/output/restructure/app/models/dynamic/def_generator.rb:262:in `other_regenerate_actions'
/output/restructure/app/models/activity_log.rb:663:in `other_regenerate_actions'
/root/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/activesupport-5.2.8.1/lib/active_support/callbacks.rb:426:in `block in make_lambda'
/root/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/activesupport-5.2.8.1/lib/active_support/callbacks.rb:271:in `block in simple'
/root/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/activesupport-5.2.8.1/lib/active_support/callbacks.rb:517:in `block in invoke_after'
/root/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/activesupport-5.2.8.1/lib/active_support/callbacks.rb:517:in `each'
/root/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/activesupport-5.2.8.1/lib/active_support/callbacks.rb:517:in `invoke_after'
/root/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/activesupport-5.2.8.1/lib/active_support/callbacks.rb:133:in `run_callbacks'
/root/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/activesupport-5.2.8.1/lib/active_support/callbacks.rb:816:in `_run_commit_callbacks'
/root/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/activerecord-5.2.8.1/lib/active_record/transactions.rb:347:in `committed!'
/root/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/activerecord-5.2.8.1/lib/active_record/connection_adapters/abstract/transaction.rb:128:in `commit_records'
/root/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/activerecord-5.2.8.1/lib/active_record/connection_adapters/abstract/transaction.rb:223:in `block in commit_transaction'
/root/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/activesupport-5.2.8.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:26:in `block (2 levels) in synchronize'
/root/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/activesupport-5.2.8.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
/root/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/activesupport-5.2.8.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
/root/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/activesupport-5.2.8.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
/root/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/activesupport-5.2.8.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
/root/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/activerecord-5.2.8.1/lib/active_record/connection_adapters/abstract/transaction.rb:213:in `commit_transaction'
/root/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/activerecord-5.2.8.1/lib/active_record/connection_adapters/abstract/transaction.rb:252:in `block in within_new_transaction'
/root/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/activesupport-5.2.8.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:26:in `block (2 levels) in synchronize'
/root/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/activesupport-5.2.8.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
/root/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/activesupport-5.2.8.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
/root/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/activesupport-5.2.8.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
/root/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/activesupport-5.2.8.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
/root/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/activerecord-5.2.8.1/lib/active_record/connection_adapters/abstract/transaction.rb:236:in `within_new_transaction'
/root/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/activerecord-5.2.8.1/lib/active_record/connection_adapters/abstract/database_statements.rb:267:in `transaction'
/root/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/activerecord-5.2.8.1/lib/active_record/transactions.rb:212:in `transaction'
/output/restructure/app/models/admin/app_type_import.rb:25:in `import_config'
/output/restructure/spec/setup_helper.rb:274:in `setup_app_from_import'
/output/restructure/spec/setup_helper.rb:223:in `setup_test_app'
/output/restructure/spec/rails_helper.rb:192:in `block (2 levels) in <top (required)>'
/root/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/rspec-core-3.12.0/lib/rspec/core/example.rb:457:in `instance_exec'
/root/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/rspec-core-3.12.0/lib/rspec/core/example.rb:457:in `instance_exec'
/root/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/rspec-core-3.12.0/lib/rspec/core/hooks.rb:365:in `run'
/root/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/rspec-core-3.12.0/lib/rspec/core/configuration.rb:2157:in `block in run_suite_hooks'
/root/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/rspec-core-3.12.0/lib/rspec/core/configuration.rb:2155:in `each'
/root/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/rspec-core-3.12.0/lib/rspec/core/configuration.rb:2155:in `run_suite_hooks'
/root/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/rspec-core-3.12.0/lib/rspec/core/configuration.rb:2069:in `with_suite_hooks'
/root/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/rspec-core-3.12.0/lib/rspec/core/runner.rb:116:in `block in run_specs'
/root/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/rspec-core-3.12.0/lib/rspec/core/reporter.rb:74:in `report'
/root/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/rspec-core-3.12.0/lib/rspec/core/runner.rb:115:in `run_specs'
/root/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/rspec-core-3.12.0/lib/rspec/core/runner.rb:89:in `run'
/root/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/rspec-core-3.12.0/lib/rspec/core/runner.rb:71:in `run'
/root/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/rspec-core-3.12.0/lib/rspec/core/runner.rb:45:in `invoke'
/root/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/rspec-core-3.12.0/exe/rspec:4:in `<top (required)>'

**Comment by melonistic** [comment]
There are several instances of this failure.

**Comment by melonistic** [comment]
Check if it is repeatable

**Comment by melonistic** [comment]
fixed with recent changes to the db structure
