### ISSUE TITLE
 Failure/Error: ScantronsController behaves like a standard user controller GET #index assigns all items as @vars

### ISSUE THREAD

**Issue by melonistic** [melonistic/restructure#12]
ScantronsController behaves like a standard user controller GET #index assigns all items as @vars
     Failure/Error: expect(assigns(objects_symbol)).to eq([item])

       expected: [#<Scantron id: 305, master_id: 17240, scantron_id: 1, user_id: 9708, created_at: "2023-03-07 14:42:11", updated_at: "2023-03-07 14:42:11">]
            got: #<ActiveRecord::Associations::CollectionProxy [#<Scantron id: 305, master_id: 17240, scantron_id: 1, user_id: 9708, created_at: "2023-03-07 14:42:11", updated_at: "2023-03-07 14:42:11">]>

       (compared using ==)

       Diff:
       @@ -1,7 +1,13 @@
       -[#<Scantron id: 305, master_id: 17240, scantron_id: 1, user_id: 9708, created_at: "2023-03-07 14:42:11", updated_at: "2023-03-07 14:42:11">]
       +[#<Scantron:0x000000000bd63340
       +  id: 305,
       +  master_id: 17240,
       +  scantron_id: 1,
       +  user_id: 9708,
       +  created_at: Tue, 07 Mar 2023 14:42:11 UTC +00:00,
       +  updated_at: Tue, 07 Mar 2023 14:42:11 UTC +00:00>]
     Shared Example Group: "a standard user controller" called from ./spec/controllers/scantrons_controller_spec.rb:41
     # ./spec/support/standard_user_controller.rb:52:in `block (3 levels) in <main>'

**Comment by melonistic** [comment]
Occurred in local testing

`ScantronsController behaves like a standard user controller GET #index assigns all items as @vars
     Failure/Error: expect(assigns(objects_symbol)).to eq([item])
     
       expected: [#<Scantron id: 7, master_id: 133, scantron_id: 1, user_id: 203, created_at: "2023-03-12 16:10:03.071465000 +0000", updated_at: "2023-03-12 16:10:03.071465000 +0000">]
            got: #<ActiveRecord::Associations::CollectionProxy [#<Scantron id: 7, master_id: 133, scantron_id: 1, user...ated_at: "2023-03-12 16:10:03.071465000 +0000", updated_at: "2023-03-12 16:10:03.071465000 +0000">]>
     
       (compared using ==)
     
       Diff:
       @@ -1,7 +1,13 @@
       -[#<Scantron id: 7, master_id: 133, scantron_id: 1, user_id: 203, created_at: "2023-03-12 16:10:03.071465000 +0000", updated_at: "2023-03-12 16:10:03.071465000 +0000">]
       +[#<Scantron:0x0000000117fe7460
       +  id: 7,
       +  master_id: 133,
       +  scantron_id: 1,
       +  user_id: 203,
       +  created_at: Sun, 12 Mar 2023 16:10:03.071465000 UTC +00:00,
       +  updated_at: Sun, 12 Mar 2023 16:10:03.071465000 UTC +00:00>]
       
     Shared Example Group: "a standard user controller" called from ./spec/controllers/scantrons_controller_spec.rb:41
     # ./spec/support/standard_user_controller.rb:52:in `block (3 levels) in <main>'

`

**Comment by melonistic** [comment]
These test fail locally but not consistently; on the other hand, the tests don't fail in isolation.
