### ISSUE TITLE
 Failure/Error: advanced search should test switching to advanced search and search a player

### ISSUE THREAD

**Issue by melonistic** [melonistic/restructure#16]
advanced search should test switching to advanced search and search a player
     Failure/Error: expect(@user.two_factor_setup_required?).to be_falsey, "#{@user.two_factor_auth_disabled}, #{@user.otp_secret.present?}, #{@user.otp_required_for_login}"
       false, false, false
     # ./spec/support/feature_support.rb:17:in `login'
     # ./spec/features/advanced_search_spec.rb:23:in `block (2 levels) in <main>'

**Comment by melonistic** [comment]
repeated in local testing

**Comment by melonistic** [comment]
unable to reproduce
