### ISSUE TITLE
Failure/Error: Register an incoming call records the details of an incoming call

### ISSUE THREAD

**Issue by melonistic** [melonistic/restructure#19]
Register an incoming call records the details of an incoming call
     Failure/Error: expect(find(el).text.downcase).to eq v.downcase

       expected: "the player called us"
            got: ""

       (compared using ==)
     # ./spec/support/activity_log_feature_support/log_expectations.rb:51:in `block (2 levels) in expect_log_to_show'
     # ./spec/support/activity_log_feature_support/log_expectations.rb:45:in `each'
     # ./spec/support/activity_log_feature_support/log_expectations.rb:45:in `block in expect_log_to_show'
     # ./spec/support/activity_log_feature_support/log_expectations.rb:44:in `expect_log_to_show'
     # ./spec/features/activity_log/register_call_spec.rb:79:in `block (2 levels) in <main>'

**Comment by melonistic** [comment]
has been fixed
