### ISSUE TITLE
Failure/Error: Register an incoming call records the details of an outgoing call

### ISSUE THREAD

**Issue by melonistic** [melonistic/restructure#20]
Register an incoming call records the details of an outgoing call
     Failure/Error: expect(page).to have_css(NewPhoneLogFormCss)
       expected to find css "form#new_activity_log_player_contact_phone" but there were no matches
     # ./spec/support/activity_log_feature_support/phone_list_actions.rb:58:in `select_phone_to_call'
     # ./spec/support/activity_log_feature_support/log_call_actions.rb:17:in `indicate_user_made_a_call'
     # ./spec/features/activity_log/register_call_spec.rb:91:in `block (2 levels) in <main>'

**Comment by melonistic** [comment]
The test does not fail in local testing.
