### ISSUE TITLE
Failure/Error: Register an incoming call records the details of an outgoing call to a bad number

### ISSUE THREAD

**Issue by melonistic** [melonistic/restructure#21]
Register an incoming call records the details of an outgoing call to a bad number
     Failure/Error: expect(page).to have_css(ActivityLogListBlockCss)
       expected to find css ".activity-log--player-contact-phones-block .activity-log-list" but there were no matches
     # ./spec/support/activity_log_feature_support/log_expectations.rb:31:in `expect_phone_log_to_be_visible'
     # ./spec/features/activity_log/register_call_spec.rb:107:in `block (2 levels) in <main>'

**Comment by melonistic** [comment]
The test does not fail in local testing.
