### ISSUE TITLE
Failure/Error: Create a BHS subject and activity finds a subject as PI

### ISSUE THREAD

**Issue by melonistic** [melonistic/restructure#22]
Create a BHS subject and activity finds a subject as PI
     Failure/Error: expect(logged_in_user[:title]).to eq @good_email

       expected: "g-ttuser-1678200720.2640443--@testing.com"
            got: "g-ttuser-1678200718.9553--@testing.com"

       (compared using ==)
     # ./spec/support/user_actions_setup.rb:11:in `user_logs_in'
     # ./spec/features/bhs_app/bhs_spec.rb:96:in `login_to_app'
     # ./spec/features/bhs_app/bhs_spec.rb:70:in `as_user'
     # ./spec/features/bhs_app/bhs_spec.rb:110:in `block (2 levels) in <main>'

**Comment by melonistic** [comment]
"g-ttuser-1678200720.2640443--@testing.com"
"g-ttuser-1678200718.9553--@testing.com"

**Comment by melonistic** [comment]
has been fixed
