### ISSUE TITLE
Failure/Error: Create a BHS subject and activity finds a subject as RA

### ISSUE THREAD

**Issue by melonistic** [melonistic/restructure#33]
Create a BHS subject and activity finds a subject as RA
     Failure/Error: expect(tabs.length).to eq BhsUi::TabNames.length
     
       expected: 4
            got: 3
     
       (compared using ==)
     # ./spec/support/bhs_app/bhs_expectations.rb:10:in `expect_bhs_tabs'
     # ./spec/features/bhs_app/bhs_spec.rb:127:in `block (2 levels) in <main>'

**Comment by melonistic** [comment]
The test indicates that it gets 2 tabs.

  2) Create a BHS subject and activity finds a subject as RA
     Failure/Error: expect(tabs.length).to eq BhsUi::TabNames.length
     
       expected: 4
            got: 2
     
       (compared using ==)
     # ./spec/support/bhs_app/bhs_expectations.rb:10:in `expect_bhs_tabs'
     # ./spec/features/bhs_app/bhs_spec.rb:127:in `block (2 levels) in <main>'

**Comment by melonistic** [comment]
I can reproduce this issue locally and in the VM. With the recent changes to the DB structure, the result tab count is 2 instead of 3. Nonetheless, the correct result is 4.

**Comment by melonistic** [comment]
I am able to reproduce in the VM.

**Comment by melonistic** [comment]
Phil will investigate.
