### ISSUE TITLE
Failure/Error: TrackersController PUT #update with invalid params re-renders the 'edit' template

### ISSUE THREAD

**Issue by melonistic** [melonistic/restructure#35]
TrackersController PUT #update with invalid params re-renders the 'edit' template
     Failure/Error: JSON.parse(response.body)
     
     JSON::ParserError:
       unexpected token at ''
     # ./spec/support/master_support.rb:159:in `resp'
     # ./spec/controllers/trackers_controller_spec.rb:203:in `block (4 levels) in <main>'

**Comment by melonistic** [comment]
I am able to reproduce in the VM.

**Comment by melonistic** [comment]
The request is throwing an error.

#<ActionDispatch::TestResponse:0x000000013407feb0 @mon_data=#<Monitor:0x000000013407d5c0>, @mon_data_owner_object_id=106660, @header={"X-Frame-Options"=>"SAMEORIGIN", "X-XSS-Protection"=>"1; mode=block", "X-Content-Type-Options"=>"nosniff", "X-Download-Options"=>"noopen", "X-Permitted-Cross-Domain-Policies"=>"none", "Referrer-Policy"=>"strict-origin-when-cross-origin", "Cache-Control"=>"no-store", "Pragma"=>"no-cache", "Expires"=>"Fri, 01 Jan 1990 00:00:00 GMT", "X-Upload-Errors"=>"{\"error\":[\"An unexpected error occurred. Contact the administrator if this condition persists. undefined method `join' for #\\u003cActiveModel::Error:0x000000011beff670\\u003e\"]}", "Content-Type"=>"text/html; charset=utf-8"}, @stream=#<ActionDispatch::Response::Buffer:0x000000011bedc738 @response=#<ActionDispatch::TestResponse:0x000000013407feb0 ...>, @buf=[""], @closed=false, @str_body=nil>, @status=500, @cv=#<MonitorMixin::ConditionVariable:0x000000013407ce68 @monitor=#<Monitor:0x000000013407d5c0>, @cond=#<Thread::ConditionVariable:0x000000013407cda0>>, @committed=true, @sending=false, @sent=true, @cache_control={}, @request=#<ActionController::TestRequest PUT "http://test.host/masters/2898/trackers/15577" for 0.0.0.0>>

**Comment by melonistic** [comment]
An unexpected error occurred. Contact the administrator if this condition persists. undefined method `join' for #\u003cActiveModel::Error:0x000000011beff670\u003e
