### ISSUE TITLE
Failure/Error: PlayerInfo should store all information related to a player

### ISSUE THREAD

**Issue by melonistic** [melonistic/restructure#37]
PlayerInfo should store all information related to a player
     Failure/Error: @player_info = master.player_infos.create! att

     ActiveRecord::RecordInvalid:
       Validation failed: End year is after  2024
     # ./spec/support/player_info_support.rb:82:in `create_item'
     # ./spec/support/master_support.rb:112:in `block in create_items'
     # ./spec/support/master_support.rb:111:in `each'
     # ./spec/support/master_support.rb:111:in `create_items'
     # ./spec/models/player_info_spec.rb:28:in `block (2 levels) in <main>'

**Comment by melonistic** [comment]
This issue cannot be reproduced consistently. I suspect that this issue occurs when clean up is not executed before testing, so it might be due to improper clean up of the DB records.

**Comment by melonistic** [comment]
Unable to reproduce
